### ISSUE TITLE
Figshare model.yaml vs model.yml naming convention

### ISSUE THREAD

**Issue by tobigithub** [kusterlab/prosit#23]
Hi,
the file from figshare model_irt_prediction contains the file model.**yaml**
this file needs to be renamed in order to run Prosit to **model.yml**

Source: https://figshare.com/articles/Prosit_-_Model_-_iRT/6965801
File: model_irt_prediction.zip (24.32 MB)

![image](https://user-images.githubusercontent.com/2569565/66885368-f23a2b80-ef88-11e9-8210-ed071163431e.png)

The wrong extension leads to the following error:

````
make server MODEL_SPECTRA=/home/user/prosit/prosit-msms/ MODEL_IRT=/h
ome/user/prosit/prosit-iRT-old/
nvidia-docker build -qf Dockerfile -t prosit .
sha256:6e9b31cbdd7dae5f13dfa123305fed90ac8d1b39c15a10262e119cd7a68ed6b2
nvidia-docker run -it \
    -v "/home/user/prosit/prosit-msms/":/root/model_spectra/ \
    -v "/home/user/prosit/prosit-iRT-old/":/root/model_irt/ \
    -e CUDA_VISIBLE_DEVICES=0 \
    -p 5000:5000 \
    prosit python3 -m prosit.server
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/prosit/server.py", line 100, in <module>
    trained=True)
  File "/root/prosit/model.py", line 39, in load
    with open(model_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/model_irt/model.yml'
Makefile:17: recipe for target 'server' failed
make: *** [server] Error 1
user@nvidia-ngc-image-1-prosit-vm:~/prosit$
````

Reason: the source code defines the filename as model.yml, see prosit/model.py

![image](https://user-images.githubusercontent.com/2569565/66885471-404f2f00-ef89-11e9-9ac5-fbf53eafb9f4.png)

Thank you.

**Comment by gessulat** [comment]
Thank you for pointing this out!
