### ISSUE TITLE
Rescoring Error: "need at least one array to concatenate make"

### ISSUE THREAD

**Issue by rababerladuseladim** [kusterlab/prosit#40]
Hey,
I am trying to rescore a MaxQuant result and get the following error: 

```
Traceback (most recent call last): 
File "oktoberfest/grpc_alignment.py", line 31, in <module> disable_progress_bar = True) 
File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/predictPROSIT.py", line 133, in predict pred_object.predict(disable_progress_bar) 
File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/PredObject.py", line 116, in predict disable_progress_bar=disable_progress_bar) 
File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/PredObject.py", line 106, in send_requests predictions = np.vstack(predictions) 
File "<__array_function__ internals>", line 6, in vstack 
File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/numpy/core/shape_base.py", line 283, in vstack return _nx.concatenate(arrs, 0) 
File "<__array_function__ internals>", line 6, in concatenate 
ValueError: need at least one array to concatenate make: *** [calibration] Error 6
```

**Comment by LLautenbacher** [comment]
Could you provide us your task ID?
Best,
Ludwig

**Comment by rababerladuseladim** [comment]
Sure: A66FCCB2F25B7178399DFF78EAB575E3

**Comment by LLautenbacher** [comment]
Hi,

sorry for the late answer! I checked your job,  you used an ITMS mass analyzer for acquiring your spectra. Since the available Prosit model was trained on FTMS data we only support FTMS data at the moment.

Best,
Ludwig
