### ISSUE TITLE
Error code gotten in one of 20 parts

### ISSUE THREAD

**Issue by phil812** [kusterlab/prosit#81]
Hello,
Earlier today I submitted a 20 smaller CSV parts to the Prosit server. 19 of them worked very fast in fine without any problems. However, for the seventh part (Task ID C73B76C2B33D44D1DDBE6F19582546E3) I got the following error code:

An error occured. Status code: 2
    Error log
    keyboard_arrow_down
    2022-01-27 13:46:09.734102: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory 2022-01-27 13:46:09.734136: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine. Traceback (most recent call last): File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/root/oktoberfest/__main__.py", line 8, in <module> main() File "/root/oktoberfest/oktoberfest.py", line 35, in main run_oktoberfest(args.search_dir, args.config_path) File "/root/oktoberfest/oktoberfest.py", line 160, in run_oktoberfest generate_spectral_lib(search_dir, config_path) File "/root/oktoberfest/oktoberfest.py", line 88, in generate_spectral_lib spec_library.library.spectra_data['MASS'] = spec_library.library.spectra_data['MODIFIED_SEQUENCE'].apply( File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 4357, in apply return SeriesApply(self, func, convert_dtype, args, kwargs).apply() File "/usr/local/lib/python3.8/site-packages/pandas/core/apply.py", line 1043, in apply return self.apply_standard() File "/usr/local/lib/python3.8/site-packages/pandas/core/apply.py", line 1098, in apply_standard mapped = lib.map_infer( File "pandas/_libs/lib.pyx", line 2859, in pandas._libs.lib.map_infer File "/root/oktoberfest/oktoberfest.py", line 89, in <lambda> lambda x: compute_peptide_mass(x)) File "/usr/local/lib/python3.8/site-packages/fundamentals/fragments.py", line 84, in compute_peptide_mass forward_sum += constants.AA_MASSES[peptide_sequence[i]] # sum left to right KeyError: '_' make: *** [/oktoberfest/Makefile:23: run_oktoberfest] Error 2

I am rather confused, as all other parts worked fine. Could you help me?

Thank you very much in advance,
Philip

**Comment by WassimG** [comment]
Hey Philip,

This is because in this file you have couple of peptides with _ inside the sequence and we can't read such a character. I am not sure what it is supposed to be but you can remove these sequences and then it should work.
Fyi we are supporting bigger csv files now so you don't have to split them anymore.

Best,
Wassim
