### ISSUE TITLE
Error when running TMT models

### ISSUE THREAD

**Issue by yangkl96** [kusterlab/prosit#87]
Hello,

I tried running the following file
[spectraRT.csv](https://github.com/kusterlab/prosit/files/9105191/spectraRT.csv)
with the TMT models but received this error. How can I resolve it?

`2022-07-13 19:04:21.460469: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory 2022-07-13 19:04:21.460504: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine. /root/oktoberfest/spectral_library.py:94: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame. Try using .loc[row_indexer,col_indexer] = value instead See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy library.spectra_data['FRAGMENTATION_GRPC'] = library.spectra_data["FRAGMENTATION"].apply(lambda x : 2 if x=='HCD' else 1) Traceback (most recent call last): File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/root/oktoberfest/__main__.py", line 8, in <module> main() File "/root/oktoberfest/oktoberfest.py", line 35, in main run_oktoberfest(args.search_dir, args.config_path) File "/root/oktoberfest/oktoberfest.py", line 177, in run_oktoberfest generate_spectral_lib(search_dir, config_path) File "/root/oktoberfest/oktoberfest.py", line 121, in generate_spectral_lib grpc_output_sec = spec_library.grpc_predict(spectra_div) File "/root/oktoberfest/spectral_library.py", line 95, in grpc_predict predictions,sequences = predictor.predict(sequences=library.spectra_data["MODIFIED_SEQUENCE"].values.tolist(), File "/usr/local/lib/python3.8/site-packages/prosit_grpc/predictPROSIT.py", line 134, in predict raise ValueError(f"The models {models_not_available} are not available at the Prosit server") ValueError: The models ['Prosit_TMT_intensity_2021', 'Prosit_TMT_irt_2021'] are not available at the Prosit server make: *** [/oktoberfest/Makefile:23: run_oktoberfest] Error 2`

Thanks,
Kevin

**Comment by levitsky** [comment]
I have the same error with non-TMT models.
